#!/usr/bin/env bash

# Function to get DNS record information
get_dns_info() {
    local subdomain=$1
    local domain=$2
    dig +short "${subdomain}.${domain}" | while read -r ip; do
        if [[ -n $ip ]]; then
            echo "The subdomain ${subdomain} is a A record and points to ${ip}"
        fi
    done
}

# Main function
main() {
    local domain=$1
    local subdomain=$2

    if [[ -z $subdomain ]]; then
        get_dns_info "www" $domain
        get_dns_info "lb-01" $domain
        get_dns_info "web-01" $domain
        get_dns_info "web-02" $domain
    else
        get_dns_info $subdomain $domain
    fi
}

# Check if domain is provided
if [[ -z $1 ]]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

# Call the main function with the provided arguments
main $1 $2
